// <auto-generated />
using AnimalShelterServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalsServer.Solution.Migrations
{
    [DbContext(typeof(AnimalShelterServerContext))]
    partial class AnimalShelterServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AnimalShelterServer.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnimalNote");

                    b.Property<int>("AnimalNumber");

                    b.Property<string>("AnimalText");

                    b.Property<string>("UserName");

                    b.HasKey("AnimalId");

                    b.ToTable("animals");
                });
#pragma warning restore 612, 618
        }
    }
}
